### ISSUE TITLE
利用してるエコシステム類のバージョンを最新に合わせる

### ISSUE THREAD

**Issue by MasayaAoyama** [cloudnativedaysjp/cicd-handson-2021#89]

**Comment by cyberblack28** [comment]
@makocchi-git Chapter8のArgo周りお願いします。
@naka-teruhisa Chapter3でバージョン最新にする必要のあるものをチェックして、必要あれば修正お願いします。
@cyberblack28 Chapter0は私の方で対応します。

**Comment by cyberblack28** [comment]
マージ完了 クローズします。
